COMPONENT = BlinkRadioAppC
PFLAGS += -I$(TOSDIR)/lib/printf
PFLAGS += -I$(TOSDIR)/sensorboards/mts400
PFLAGS += -I$(TOSDIR)/lib/net/tymo
PFLAGS += -I$(TOSDIR)/lib/net/tymo/dymo
PFLAGS += -I$(TOSDIR)/lib/net/tymo/mh
include $(MAKERULES)